### ISSUE TITLE
Install script path (OctoPi) 

### ISSUE THREAD

**Issue by shaunbro** [OutsourcedGuru/OctoPrint-USBControl#2]
Relatively new to this and always forget OctoPi != OctoPrint so just in case it is helpful the path for the install script for OctoPi is
~pi/oprint/lib/python2.7/site-packages/usbcontrol/bin/install

**Comment by OutsourcedGuru** [comment]
I updated the docs to include this information but of course it appears in the Settings screen when the plugin has been freshly installed.

And actually, the command and path is this:

`sudo ~/oprint/lib/python2.7/site-packages/usbcontrol/bin/install`

**Comment by shaunbro** [comment]
Apologies I can see why I got that wrong now - I was not running as the
user 'pi' the ~ path is obviously relative to the user and in my case I was
using my own user account so the path for me and any user other than 'pi' is
either

~pi/oprint/...
or (imho better)
/home/pi/oprint/...

I accept that the issue is/was caused by my modifications to an otherwise
vanilla octopi image so perhaps no change to your doc needed.
I can't not mention how absolute paths make this a non issue for all
players,  but each to their own and thanks for the great plugin!

**Comment by OutsourcedGuru** [comment]
Gotcha. Duly-noted.
