### ISSUE TITLE
Enhancement: install uhubctl to /usr/local/bin (or /usr/local/sbin)

### ISSUE THREAD

**Issue by b-morgan** [OutsourcedGuru/OctoPrint-USBControl#4]
I'd like to be able to run uhubctl from an SSH session without searching for it. If it is installed in /usr/local/bin or /usr/local/sbin then I can do so with just "sudo uhubctl". I believe the plugin could also run it from there. If you wish to make this optional, I'm happy with answering an additional question during the install process.

**Comment by OutsourcedGuru** [comment]
It's not a bad idea. The average person wouldn't even know that it's there so I placed it under the plugin's umbrella, so-to-speak. I'll likely just add a symlink in the `/usr/local/bin` folder which just points back to the executable, though, for what it's worth.

**Comment by b-morgan** [comment]
Works for me.

**Comment by OutsourcedGuru** [comment]
Although I've added this to v1.0.7, if you've already initialized on your system then you'd need to manually create the symlink yourself.

`ln -s /home/pi/oprint/lib/python2.7/site-packages/usbcontrol/bin/uhubctl /usr/local/bin/uhubctl`
